echo -e '\x1b[33m'
echo -e '                                                                   '
echo -e ' /MM      /MM  /MMMMMM  /MM   /MM  /MMMMMM  /MM      /MM /MMMMMMM  '
echo -e '| MMM    /MMM /MM__  MM| MM  | MM /MM__  MM| MMM    /MMM| MM__  MM '
echo -e '| MMMM  /MMMM| MM  \ MM| MM  | MM| MM  \ MM| MMMM  /MMMM| MM  \ MM '
echo -e '| MM MM/MM MM| MMMMMMMM| MMMMMMMM| MMMMMMMM| MM MM/MM MM| MMMMMMM  '
echo -e '| MM  MMM| MM| MM__  MM| MM__  MM| MM__  MM| MM  MMM| MM| MM__  MM '
echo -e '| MM\  M | MM| MM  | MM| MM  | MM| MM  | MM| MM\  M | MM| MM  \ MM '
echo -e '| MM \/  | MM| MM  | MM| MM  | MM| MM  | MM| MM \/  | MM| MMMMMMM/ '
echo -e '|__/     |__/|__/  |__/|__/  |__/|__/  |__/|__/     |__/|_______/  '
echo -e '                                                                   '
echo -e '                                                                   '
echo -e '                                                                   '
echo -e ' /MM   /MM  /MMMMMM  /MMMMMMM  /MMMMMMMM  /MMMMMM                  '
echo -e '| MMM | MM /MM__  MM| MM__  MM| MM_____/ /MM__  MM                 '
echo -e '| MMMM| MM| MM  \ MM| MM  \ MM| MM      | MM  \__/                 '
echo -e '| MM MM MM| MM  | MM| MM  | MM| MMMMM   |  MMMMMM                  '
echo -e '| MM  MMMM| MM  | MM| MM  | MM| MM__/    \____  MM                 '
echo -e '| MM\  MMM| MM  | MM| MM  | MM| MM       /MM  \ MM                 '
echo -e '| MM \  MM|  MMMMMM/| MMMMMMM/| MMMMMMMM|  MMMMMM/                 '
echo -e '|__/  \__/ \______/ |_______/ |________/ \______/                  '
echo -e '                                                                   '
echo -e '\x1b[0m'
